package cz.mendelu.pef.xdostal8.saywhatsnap.mock

import cz.mendelu.pef.xdostal8.saywhatsnap.model.database.TranslationEntity

object TranslationsMock {


    val listOfCat = listOf("Kategorie", "Category")

    // id is autogenerated... for testing purposes static id
    const val todayTransId = 1L
    const val yesterdayTransId = 2L

    //id 1
    //today = 1
    val todayTranslation = TranslationEntity(
        originalString = "Dnes",
        originalLanguage = "cs",
        translatedString = "Today",
        translatedLanguage = "en",
        date = 1,
        image = "Dnes",
        name = "Dnes",
        latitude = 0.0,
        longitude = 0.0,
        category = listOfCat[0],
        description = "Popis",
        visible = true
    )

    //id2
    //yesterday = 2
    val yesterdayTranslation = TranslationEntity(
        originalString = "Yesterday",
        originalLanguage = "en",
        translatedString = "Včera",
        translatedLanguage = "cs",
        category = listOfCat[1],
        description = "Description",
        visible = false,
        name = "Yesterday",
        image = "Yesterday",
        date = 2,
        latitude = 50.0,
        longitude = 15.0,
    )
}